template: |
  ## What's Changed
  This release includes the following changes pulled from merged PRs.

  $CHANGES

  ## Contributors
  Thank you to all contributors!

change-template: "### Changes\n$CHANGES"
