name: Mirror main to main-backup

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1' # 매주 월요일 UTC 03:00 (로컬 시간에 맞추려면 조정하세요)

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    concurrency:
      group: mirror-main
      cancel-in-progress: false
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create or update main-backup
        run: |
          TARGET_BRANCH=main-backup
          # Create local branch from main
          git checkout -B "$TARGET_BRANCH"
          # Force push to update mirror (this handles history rewrites)
          git push --force origin "$TARGET_BRANCH"

      - name: Create issue on failure
        if: failure()
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Mirror workflow failed: main -> main-backup'
          body: |
            The mirror workflow failed for commit `${{ github.sha }}` on branch `main`.
            Please check the workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            This issue was created automatically.
          labels: mirror, automated

      - name: Cleanup
        run: git checkout -
