name: Pages smoke check

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch: {}

jobs:
  smoke:
    name: Smoke check GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Lightweight smoke test
        run: |
          set -euo pipefail
          REPO_FULL="${{ github.repository }}"
          OWNER="${REPO_FULL%%/*}"
          NAME="${REPO_FULL##*/}"
          URL="https://${OWNER}.github.io/${NAME}/"
          echo "Checking Pages URL: $URL"

          # root must return 200
          HTTP=$(curl -fsS -o /dev/null -w "%{http_code}" "$URL" || true)
          if [ "$HTTP" != "200" ]; then
            echo "ERROR: site root returned HTTP $HTTP"
            curl -fsS -I "$URL" || true
            exit 1
          fi

          HTML=$(curl -fsS "$URL")
          echo "$HTML" | sed -n '1,60p' > site.html

          # basic assertion: root div exists
          echo "Checking for <div id=\"root\">..."
          echo "$HTML" | grep -q '<div id="root"' || (echo "ERROR: root div not found" && exit 1)

          # find asset paths referenced under /<repo>/assets/
          ASSETS=$(echo "$HTML" | grep -oE "/${NAME}/assets/[^\"'\s>]+" | sort -u || true)
          if [ -z "$ASSETS" ]; then
            echo "WARNING: no assets found in HTML — nothing to check"
            exit 0
          fi

          echo "Found assets:" && echo "$ASSETS"
          for a in $ASSETS; do
            FULL="https://${OWNER}.github.io${a}"
            echo "Checking asset: $FULL"
            HTTP=$(curl -fsS -o /dev/null -w "%{http_code}" "$FULL" || true)
            if [ "$HTTP" != "200" ]; then
              echo "ERROR: asset $FULL returned $HTTP"
              curl -fsS -I "$FULL" || true
              exit 1
            fi
          done

          echo "Pages smoke test passed: root + assets OK"
