name: Weekly release integrity check

on:
  schedule:
    - cron: '0 5 * * 1' # Weekly on Monday 05:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check-latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gh CLI
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install -y gh
          fi

      - name: Get latest release tag
        id: get_release
        run: |
          TAG=$(gh release list --repo ${{ github.repository }} --limit 1 --json tagName -q '.[0].tagName')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Verify presence of zip and sha256
        run: |
          set -euo pipefail
          TAG=${{ steps.get_release.outputs.tag }}
          echo "Checking release $TAG"
          ASSETS=$(gh release view "$TAG" --repo ${{ github.repository }} --json assets -q '.assets[].name') || (echo "Release or assets not found" && exit 1)
          echo "$ASSETS" | grep -q "VisualCode-dist-${TAG}.zip" || (echo "ZIP asset missing for $TAG" && exit 1)
          echo "$ASSETS" | grep -q "VisualCode-dist-${TAG}.sha256" || (echo "SHA256 asset missing for $TAG" && exit 1)
